using EK7TKN_HFT_2021221.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace EK7TKN_HFT_2021221.Data
{
    public class xDbContext : DbContext
    {
        //Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True

        public  DbSet<RunInformation> Runs { get; set; }
        public  DbSet<PasswordSecurity> Passwords { get; set; }
        public  DbSet<UserInformation> Users { get; set; }

        public xDbContext(DbContextOptions<xDbContext> options) : base(options)
        {
            this.Database.EnsureCreated();
        }
        public xDbContext() 
        {
            Database?.EnsureCreated();
        }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder
                   

                    .UseLazyLoadingProxies()
                    .UseSqlServer(@"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database1.mdf;Integrated Security=True");

            }
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            List<UserInformation> listau = new List<UserInformation>()
            {
new UserInformation() { full_Name=" Test     ",email="	kwaghorne0@soundcloud.com	",age=  41  ,height=    186 ,weight=    82  ,userID=    1   ,premium=   false   },
new UserInformation() { full_Name="	Desiri Wardington	",email="	dwardington1@rediff.com	",age=  27  ,height=    179 ,weight=    71  ,userID=    2   ,premium=   true    },
new UserInformation() { full_Name="	Kale Maynard	",email="	kmaynard2@wisc.edu	",age=  50  ,height=    174 ,weight=    65  ,userID=    3   ,premium=   true    },
new UserInformation() { full_Name="	Dale Brannan	",email="	dbrannan3@godaddy.com	",age=  62  ,height=    196 ,weight=    66  ,userID=    4   ,premium=   false   },
new UserInformation() { full_Name="	Haleigh Finessy	",email="	hfinessy4@ucoz.com	",age=  31  ,height=    182 ,weight=    99  ,userID=    5   ,premium=   false   },
new UserInformation() { full_Name="	Joe Petroselli	",email="	jpetroselli5@symantec.com	",age=  55  ,height=    173 ,weight=    103 ,userID=    6   ,premium=   false   },
new UserInformation() { full_Name="	Gwenny Haysom	",email="	ghaysom6@wp.com	",age=  71  ,height=    170 ,weight=    68  ,userID=    7   ,premium=   false   },
new UserInformation() { full_Name="	Dita Fyfe	",email="	dfyfe7@ox.ac.uk	",age=  50  ,height=    175 ,weight=    85  ,userID=    8   ,premium=   false   },
new UserInformation() { full_Name="	Dennet Isselee	",email="	disselee8@networksolutions.com	",age=  80  ,height=    183 ,weight=    64  ,userID=    9   ,premium=   true    },
new UserInformation() { full_Name="	Ricca Penrose	",email="	rpenrose9@topsy.com	",age=  36  ,height=    176 ,weight=    83  ,userID=    10  ,premium=   true    },
new UserInformation() { full_Name="	Lamar O'Hannay	",email="	lohannaya@storify.com	",age=  53  ,height=    168 ,weight=    109 ,userID=    11  ,premium=   false   },
new UserInformation() { full_Name="	Walsh Crookston	",email="	wcrookstonb@mlb.com	",age=  49  ,height=    177 ,weight=    76  ,userID=    12  ,premium=   false   },
new UserInformation() { full_Name="	Kath Discombe	",email="	kdiscombec@bbb.org	",age=  46  ,height=    187 ,weight=    102 ,userID=    13  ,premium=   false   },
new UserInformation() { full_Name="	Stirling Alleburton	",email="	salleburtond@thetimes.co.uk	",age=  45  ,height=    172 ,weight=    77  ,userID=    14  ,premium=   true    },
new UserInformation() { full_Name="	Ralf Lunney	",email="	rlunneye@typepad.com	",age=  47  ,height=    164 ,weight=    93  ,userID=    15  ,premium=   false   },
new UserInformation() { full_Name="	Hebert Guillotin	",email="	hguillotinf@bigcartel.com	",age=  36  ,height=    193 ,weight=    80  ,userID=    16  ,premium=   false   },
new UserInformation() { full_Name="	Emera Routledge	",email="	eroutledgeg@google.com.au	",age=  30  ,height=    167 ,weight=    98  ,userID=    17  ,premium=   true    },
new UserInformation() { full_Name="	Cristine Ianiello	",email="	cianielloh@discuz.net	",age=  38  ,height=    198 ,weight=    94  ,userID=    18  ,premium=   false   },
new UserInformation() { full_Name="	Gertrudis Beevers	",email="	gbeeversi@howstuffworks.com	",age=  64  ,height=    179 ,weight=    107 ,userID=    19  ,premium=   false   },
new UserInformation() { full_Name="	Orsa Stean	",email="	osteanj@dedecms.com	",age=  20  ,height=    197 ,weight=    62  ,userID=    20  ,premium=   true    },
new UserInformation() { full_Name="	Millicent Bouchier	",email="	mbouchierk@gravatar.com	",age=  43  ,height=    193 ,weight=    98  ,userID=    21  ,premium=   false   },
new UserInformation() { full_Name="	Ema Penylton	",email="	epenyltonl@webmd.com	",age=  59  ,height=    184 ,weight=    88  ,userID=    22  ,premium=   true    },
new UserInformation() { full_Name="	Gabbie Batterson	",email="	gbattersonm@plala.or.jp	",age=  40  ,height=    188 ,weight=    61  ,userID=    23  ,premium=   true    },
new UserInformation() { full_Name="	Rebe Senner	",email="	rsennern@instagram.com	",age=  64  ,height=    181 ,weight=    93  ,userID=    24  ,premium=   true    },
new UserInformation() { full_Name="	Del Hoofe	",email="	dhoofeo@epa.gov	",age=  47  ,height=    174 ,weight=    98  ,userID=    25  ,premium=   false   },
new UserInformation() { full_Name="	Jillana Overbury	",email="	joverburyp@1688.com	",age=  59  ,height=    169 ,weight=    65  ,userID=    26  ,premium=   false   },
new UserInformation() { full_Name="	Lorrayne Trodler	",email="	ltrodlerq@tumblr.com	",age=  41  ,height=    168 ,weight=    79  ,userID=    27  ,premium=   false   },
new UserInformation() { full_Name="	Edna Ewan	",email="	eewanr@blogger.com	",age=  25  ,height=    171 ,weight=    64  ,userID=    28  ,premium=   true    },
new UserInformation() { full_Name="	Catie Dilworth	",email="	cdilworths@amazon.co.uk	",age=  34  ,height=    169 ,weight=    99  ,userID=    29  ,premium=   true    },
new UserInformation() { full_Name="	Lissi McEntegart	",email="	lmcentegartt@pagesperso-orange.fr	",age=  46  ,height=    182 ,weight=    104 ,userID=    30  ,premium=   true    },
new UserInformation() { full_Name="	Lilllie Meier	",email="	lmeieru@uiuc.edu	",age=  64  ,height=    179 ,weight=    67  ,userID=    31  ,premium=   false   },
new UserInformation() { full_Name="	Dyanne Brinicombe	",email="	dbrinicombev@arizona.edu	",age=  66  ,height=    175 ,weight=    100 ,userID=    32  ,premium=   true    },
new UserInformation() { full_Name="	Ashlie Nyssens	",email="	anyssensw@army.mil	",age=  31  ,height=    184 ,weight=    94  ,userID=    33  ,premium=   true    },
new UserInformation() { full_Name="	Romy Baynon	",email="	rbaynonx@sciencedirect.com	",age=  38  ,height=    187 ,weight=    89  ,userID=    34  ,premium=   false   },
new UserInformation() { full_Name="	Harli Vercruysse	",email="	hvercruyssey@so-net.ne.jp	",age=  32  ,height=    177 ,weight=    65  ,userID=    35  ,premium=   true    },
new UserInformation() { full_Name="	Stuart Thornham	",email="	sthornhamz@technorati.com	",age=  40  ,height=    166 ,weight=    98  ,userID=    36  ,premium=   false   },
new UserInformation() { full_Name="	Morganica Hebborn	",email="	mhebborn10@is.gd	",age=  57  ,height=    167 ,weight=    100 ,userID=    37  ,premium=   true    },
new UserInformation() { full_Name="	Jacob Klaus	",email="	jklaus11@nasa.gov	",age=  75  ,height=    186 ,weight=    100 ,userID=    38  ,premium=   false   },
new UserInformation() { full_Name="	Kirbie Healing	",email="	khealing12@spiegel.de	",age=  32  ,height=    194 ,weight=    103 ,userID=    39  ,premium=   true    },
new UserInformation() { full_Name="	Adrianna Theunissen	",email="	atheunissen13@sitemeter.com	",age=  15  ,height=    165 ,weight=    88  ,userID=    40  ,premium=   true    },
new UserInformation() { full_Name="	Elena Blazej	",email="	eblazej14@blogtalkradio.com	",age=  80  ,height=    191 ,weight=    60  ,userID=    41  ,premium=   false   },
new UserInformation() { full_Name="	Bent Vern	",email="	bvern15@npr.org	",age=  45  ,height=    183 ,weight=    77  ,userID=    42  ,premium=   false   },
new UserInformation() { full_Name="	Mayor Slogrove	",email="	mslogrove16@jigsy.com	",age=  40  ,height=    180 ,weight=    89  ,userID=    43  ,premium=   true    },
new UserInformation() { full_Name="	Ramon Ortiger	",email="	rortiger17@home.pl	",age=  48  ,height=    166 ,weight=    110 ,userID=    44  ,premium=   false   },
new UserInformation() { full_Name="	Marissa Bridgestock	",email="	mbridgestock18@freewebs.com	",age=  45  ,height=    180 ,weight=    102 ,userID=    45  ,premium=   false   },
new UserInformation() { full_Name="	Clark Yendall	",email="	cyendall19@addthis.com	",age=  76  ,height=    164 ,weight=    66  ,userID=    46  ,premium=   false   },
new UserInformation() { full_Name="	Lucia Frankis	",email="	lfrankis1a@yandex.ru	",age=  61  ,height=    190 ,weight=    86  ,userID=    47  ,premium=   false   },
new UserInformation() { full_Name="	Deb Moyne	",email="	dmoyne1b@gizmodo.com	",age=  49  ,height=    198 ,weight=    107 ,userID=    48  ,premium=   false   },
new UserInformation() { full_Name="	Hercule Wewell	",email="	hwewell1c@hp.com	",age=  48  ,height=    179 ,weight=    66  ,userID=    49  ,premium=   true    },
new UserInformation() { full_Name="	Fianna Fullman	",email="	ffullman1d@google.ca	",age=  41  ,height=    170 ,weight=    89  ,userID=    50  ,premium=   true    },
new UserInformation() { full_Name="	Miguela Hassett	",email="	mhassett1e@gravatar.com	",age=  45  ,height=    172 ,weight=    91  ,userID=    51  ,premium=   false   },
new UserInformation() { full_Name="	Maximo Dennitts	",email="	mdennitts1f@1und1.de	",age=  60  ,height=    178 ,weight=    94  ,userID=    52  ,premium=   true    },
new UserInformation() { full_Name="	Diana Dominighi	",email="	ddominighi1g@yellowpages.com	",age=  66  ,height=    167 ,weight=    94  ,userID=    53  ,premium=   true    },
new UserInformation() { full_Name="	Allyn Heiden	",email="	aheiden1h@businessweek.com	",age=  25  ,height=    189 ,weight=    97  ,userID=    54  ,premium=   true    },
new UserInformation() { full_Name="	Stavro Winckworth	",email="	swinckworth1i@nymag.com	",age=  30  ,height=    175 ,weight=    101 ,userID=    55  ,premium=   true    },
new UserInformation() { full_Name="	Jo ann Beeckx	",email="	jann1j@harvard.edu	",age=  56  ,height=    186 ,weight=    76  ,userID=    56  ,premium=   false   },
new UserInformation() { full_Name="	Jere Du Pre	",email="	jdu1k@webs.com	",age=  58  ,height=    172 ,weight=    93  ,userID=    57  ,premium=   true    },
new UserInformation() { full_Name="	Christiana Shevell	",email="	cshevell1l@hhs.gov	",age=  77  ,height=    185 ,weight=    73  ,userID=    58  ,premium=   false   },
new UserInformation() { full_Name="	Lilith Parkinson	",email="	lparkinson1m@nsw.gov.au	",age=  61  ,height=    181 ,weight=    83  ,userID=    59  ,premium=   false   },
new UserInformation() { full_Name="	Berkly Crowden	",email="	bcrowden1n@moonfruit.com	",age=  49  ,height=    189 ,weight=    75  ,userID=    60  ,premium=   true    },
new UserInformation() { full_Name="	Dinnie Duigenan	",email="	dduigenan1o@geocities.jp	",age=  35  ,height=    195 ,weight=    68  ,userID=    61  ,premium=   true    },
new UserInformation() { full_Name="	Sigmund Frontczak	",email="	sfrontczak1p@goo.ne.jp	",age=  20  ,height=    177 ,weight=    86  ,userID=    62  ,premium=   false   },
new UserInformation() { full_Name="	Zechariah Hellyer	",email="	zhellyer1q@wisc.edu	",age=  17  ,height=    188 ,weight=    74  ,userID=    63  ,premium=   true    },
new UserInformation() { full_Name="	Orazio Danhel	",email="	odanhel1r@de.vu	",age=  76  ,height=    186 ,weight=    84  ,userID=    64  ,premium=   false   },
new UserInformation() { full_Name="	Carlotta Drowsfield	",email="	cdrowsfield1s@angelfire.com	",age=  77  ,height=    173 ,weight=    96  ,userID=    65  ,premium=   false   },
new UserInformation() { full_Name="	Cello Jaime	",email="	cjaime1t@usda.gov	",age=  44  ,height=    182 ,weight=    90  ,userID=    66  ,premium=   true    },
new UserInformation() { full_Name="	Gabrila Labrenz	",email="	glabrenz1u@infoseek.co.jp	",age=  80  ,height=    188 ,weight=    61  ,userID=    67  ,premium=   true    },
new UserInformation() { full_Name="	Corilla Purcer	",email="	cpurcer1v@engadget.com	",age=  51  ,height=    185 ,weight=    82  ,userID=    68  ,premium=   false   },
new UserInformation() { full_Name="	Beret Debell	",email="	bdebell1w@aol.com	",age=  79  ,height=    185 ,weight=    81  ,userID=    69  ,premium=   false   },
new UserInformation() { full_Name="	Dareen Lillgard	",email="	dlillgard1x@elegantthemes.com	",age=  33  ,height=    199 ,weight=    63  ,userID=    70  ,premium=   true    },
new UserInformation() { full_Name="	Shaun Stodhart	",email="	sstodhart1y@dagondesign.com	",age=  53  ,height=    197 ,weight=    97  ,userID=    71  ,premium=   false   },
new UserInformation() { full_Name="	Alice MacLaig	",email="	amaclaig1z@time.com	",age=  17  ,height=    195 ,weight=    96  ,userID=    72  ,premium=   true    },
new UserInformation() { full_Name="	Papagena Critchell	",email="	pcritchell20@bandcamp.com	",age=  28  ,height=    184 ,weight=    88  ,userID=    73  ,premium=   true    },
new UserInformation() { full_Name="	Ottilie Disdel	",email="	odisdel21@zimbio.com	",age=  24  ,height=    191 ,weight=    63  ,userID=    74  ,premium=   true    },
new UserInformation() { full_Name="	Jammal Stille	",email="	jstille22@lycos.com	",age=  51  ,height=    188 ,weight=    81  ,userID=    75  ,premium=   false   },
new UserInformation() { full_Name="	Othello Keller	",email="	okeller23@wikipedia.org	",age=  76  ,height=    188 ,weight=    83  ,userID=    76  ,premium=   true    },
new UserInformation() { full_Name="	Tann Mably	",email="	tmably24@omniture.com	",age=  56  ,height=    189 ,weight=    77  ,userID=    77  ,premium=   false   },
new UserInformation() { full_Name="	Liane Seawell	",email="	lseawell25@amazon.com	",age=  65  ,height=    195 ,weight=    79  ,userID=    78  ,premium=   false   },
new UserInformation() { full_Name="	Thom Rossoni	",email="	trossoni26@hao123.com	",age=  26  ,height=    196 ,weight=    62  ,userID=    79  ,premium=   false   },
new UserInformation() { full_Name="	Brodie Wyre	",email="	bwyre27@dagondesign.com	",age=  59  ,height=    178 ,weight=    80  ,userID=    80  ,premium=   true    },
new UserInformation() { full_Name="	Dehlia Richardt	",email="	drichardt28@pbs.org	",age=  51  ,height=    178 ,weight=    98  ,userID=    81  ,premium=   true    },
new UserInformation() { full_Name="	Zollie Kayes	",email="	zkayes29@fc2.com	",age=  41  ,height=    187 ,weight=    62  ,userID=    82  ,premium=   true    },
new UserInformation() { full_Name="	Ingeberg Lillecrap	",email="	ilillecrap2a@amazonaws.com	",age=  45  ,height=    190 ,weight=    100 ,userID=    83  ,premium=   false   },
new UserInformation() { full_Name="	Prentice Radin	",email="	pradin2b@e-recht24.de	",age=  52  ,height=    164 ,weight=    68  ,userID=    84  ,premium=   false   },
new UserInformation() { full_Name="	Sallyann Ellingford	",email="	sellingford2c@sakura.ne.jp	",age=  32  ,height=    165 ,weight=    83  ,userID=    85  ,premium=   false   },
new UserInformation() { full_Name="	Clarabelle Kiwitz	",email="	ckiwitz2d@ted.com	",age=  79  ,height=    164 ,weight=    78  ,userID=    86  ,premium=   true    },
new UserInformation() { full_Name="	Pattin Vaen	",email="	pvaen2e@dailymotion.com	",age=  23  ,height=    173 ,weight=    79  ,userID=    87  ,premium=   true    },
new UserInformation() { full_Name="	Marilin Dewick	",email="	mdewick2f@dion.ne.jp	",age=  22  ,height=    168 ,weight=    82  ,userID=    88  ,premium=   false   },
new UserInformation() { full_Name="	Hyacinthie McCarrell	",email="	hmccarrell2g@discovery.com	",age=  50  ,height=    199 ,weight=    86  ,userID=    89  ,premium=   true    },
new UserInformation() { full_Name="	Bill McIlvenna	",email="	bmcilvenna2h@pcworld.com	",age=  35  ,height=    188 ,weight=    66  ,userID=    90  ,premium=   false   },
new UserInformation() { full_Name="	Granthem Dureden	",email="	gdureden2i@360.cn	",age=  80  ,height=    198 ,weight=    92  ,userID=    91  ,premium=   true    },
new UserInformation() { full_Name="	Chickie Telling	",email="	ctelling2j@gmpg.org	",age=  27  ,height=    166 ,weight=    85  ,userID=    92  ,premium=   true    },
new UserInformation() { full_Name="	Seward Sofe	",email="	ssofe2k@imdb.com	",age=  17  ,height=    199 ,weight=    101 ,userID=    93  ,premium=   false   },
new UserInformation() { full_Name="	Alf Geockle	",email="	ageockle2l@unicef.org	",age=  41  ,height=    193 ,weight=    98  ,userID=    94  ,premium=   true    },
new UserInformation() { full_Name="	Margette Trinder	",email="	mtrinder2m@example.com	",age=  35  ,height=    169 ,weight=    95  ,userID=    95  ,premium=   true    },
new UserInformation() { full_Name="	Lynsey Shawl	",email="	lshawl2n@hostgator.com	",age=  75  ,height=    164 ,weight=    61  ,userID=    96  ,premium=   false   },
new UserInformation() { full_Name="	Anna-diane Salack	",email="	asalack2o@parallels.com	",age=  25  ,height=    196 ,weight=    104 ,userID=    97  ,premium=   true    },
new UserInformation() { full_Name="	Zorah MacCafferky	",email="	zmaccafferky2p@woothemes.com	",age=  55  ,height=    178 ,weight=    81  ,userID=    98  ,premium=   false   },
new UserInformation() { full_Name="	Ronny Whimp	",email="	rwhimp2q@umich.edu	",age=  62  ,height=    195 ,weight=    87  ,userID=    99  ,premium=   false   },
new UserInformation() { full_Name="	Janey Sherington	",email="	jsherington2r@ihg.com	",age=  46  ,height=    168 ,weight=    85  ,userID=    100 ,premium=   true    }

        };

            List<PasswordSecurity> lista2 = new List<PasswordSecurity>() {
new PasswordSecurity() { PassId=    1   ,UserId=    1   ,TotallySecuredVeryHashedPassword="123",RecoverPhoneNumber="	06 404 3684"}, //7ZK4pmNX
new PasswordSecurity() { PassId=    2   ,UserId=    2   ,TotallySecuredVeryHashedPassword="	m2kSx1Nw	",RecoverPhoneNumber="	06 815 6835"},
new PasswordSecurity() { PassId=    3   ,UserId=    3   ,TotallySecuredVeryHashedPassword="	JcPogOYSCZr3	",RecoverPhoneNumber="	06 684 7755"},
new PasswordSecurity() { PassId=    4   ,UserId=    4   ,TotallySecuredVeryHashedPassword="	r0zm6JvAtVK	",RecoverPhoneNumber="	06 939 7200"},
new PasswordSecurity() { PassId=    5   ,UserId=    5   ,TotallySecuredVeryHashedPassword="	lJzeIwwX3	",RecoverPhoneNumber="	06 003 8974"},
new PasswordSecurity() { PassId=    6   ,UserId=    6   ,TotallySecuredVeryHashedPassword="	bBihMicWj1I	",RecoverPhoneNumber="	06 680 9670"},
new PasswordSecurity() { PassId=    7   ,UserId=    7   ,TotallySecuredVeryHashedPassword="	9m34e0	",RecoverPhoneNumber="	06 193 1793"},
new PasswordSecurity() { PassId=    8   ,UserId=    8   ,TotallySecuredVeryHashedPassword="	sKDtip	",RecoverPhoneNumber="	06 951 9306"},
new PasswordSecurity() { PassId=    9   ,UserId=    9   ,TotallySecuredVeryHashedPassword="	CbOjnTJ	",RecoverPhoneNumber="	06 646 9789"},
new PasswordSecurity() { PassId=    10  ,UserId=    10  ,TotallySecuredVeryHashedPassword="	ityhpk	",RecoverPhoneNumber="	06 779 2399"},
new PasswordSecurity() { PassId=    11  ,UserId=    11  ,TotallySecuredVeryHashedPassword="	JxkLyDs	",RecoverPhoneNumber="	06 499 7243"},
new PasswordSecurity() { PassId=    12  ,UserId=    12  ,TotallySecuredVeryHashedPassword="	w3mqVRcKl44	",RecoverPhoneNumber="	06 648 0843"},
new PasswordSecurity() { PassId=    13  ,UserId=    13  ,TotallySecuredVeryHashedPassword="	TgMxoC75	",RecoverPhoneNumber="	06 862 4346"},
new PasswordSecurity() { PassId=    14  ,UserId=    14  ,TotallySecuredVeryHashedPassword="	136LpublH	",RecoverPhoneNumber="	06 647 2899"},
new PasswordSecurity() { PassId=    15  ,UserId=    15  ,TotallySecuredVeryHashedPassword="	oSr0Q4t	",RecoverPhoneNumber="	06 136 7121"},
new PasswordSecurity() { PassId=    16  ,UserId=    16  ,TotallySecuredVeryHashedPassword="	SX55Uh6	",RecoverPhoneNumber="	06 044 0194"},
new PasswordSecurity() { PassId=    17  ,UserId=    17  ,TotallySecuredVeryHashedPassword="	IlGKI76t	",RecoverPhoneNumber="	06 888 2004"},
new PasswordSecurity() { PassId=    18  ,UserId=    18  ,TotallySecuredVeryHashedPassword="	Vh8NGL	",RecoverPhoneNumber="	06 633 3349"},
new PasswordSecurity() { PassId=    19  ,UserId=    19  ,TotallySecuredVeryHashedPassword="	FQERjAqxiUkA	",RecoverPhoneNumber="	06 669 5449"},
new PasswordSecurity() { PassId=    20  ,UserId=    20  ,TotallySecuredVeryHashedPassword="	ssiX0MOJCnA	",RecoverPhoneNumber="	06 866 5104"},
new PasswordSecurity() { PassId=    21  ,UserId=    21  ,TotallySecuredVeryHashedPassword="	glK9mn	",RecoverPhoneNumber="	06 221 7021"},
new PasswordSecurity() { PassId=    22  ,UserId=    22  ,TotallySecuredVeryHashedPassword="	ARMHFtbWc	",RecoverPhoneNumber="	06 489 3952"},
new PasswordSecurity() { PassId=    23  ,UserId=    23  ,TotallySecuredVeryHashedPassword="	Xqw6xA	",RecoverPhoneNumber="	06 738 7554"},
new PasswordSecurity() { PassId=    24  ,UserId=    24  ,TotallySecuredVeryHashedPassword="	yu3kNScWQX4c	",RecoverPhoneNumber="	06 086 8171"},
new PasswordSecurity() { PassId=    25  ,UserId=    25  ,TotallySecuredVeryHashedPassword="	ycYaj7eiWtUU	",RecoverPhoneNumber="	06 625 4790"},
new PasswordSecurity() { PassId=    26  ,UserId=    26  ,TotallySecuredVeryHashedPassword="	ttO7UW	",RecoverPhoneNumber="	06 162 9270"},
new PasswordSecurity() { PassId=    27  ,UserId=    27  ,TotallySecuredVeryHashedPassword="	UYFx1p0YHNV	",RecoverPhoneNumber="	06 045 7600"},
new PasswordSecurity() { PassId=    28  ,UserId=    28  ,TotallySecuredVeryHashedPassword="	X1ZnVPj2	",RecoverPhoneNumber="	06 282 0231"},
new PasswordSecurity() { PassId=    29  ,UserId=    29  ,TotallySecuredVeryHashedPassword="	miitzgJYsVD7	",RecoverPhoneNumber="	06 619 2727"},
new PasswordSecurity() { PassId=    30  ,UserId=    30  ,TotallySecuredVeryHashedPassword="	gtZtlJ	",RecoverPhoneNumber="	06 057 9828"},
new PasswordSecurity() { PassId=    31  ,UserId=    31  ,TotallySecuredVeryHashedPassword="	VVW9YMFrcH	",RecoverPhoneNumber="	06 182 3167"},
new PasswordSecurity() { PassId=    32  ,UserId=    32  ,TotallySecuredVeryHashedPassword="	a4mrgbjePPnk	",RecoverPhoneNumber="	06 067 3208"},
new PasswordSecurity() { PassId=    33  ,UserId=    33  ,TotallySecuredVeryHashedPassword="	wbXbW6dlZsG	",RecoverPhoneNumber="	06 192 4844"},
new PasswordSecurity() { PassId=    34  ,UserId=    34  ,TotallySecuredVeryHashedPassword="	865oFeGUXrS	",RecoverPhoneNumber="	06 986 5471"},
new PasswordSecurity() { PassId=    35  ,UserId=    35  ,TotallySecuredVeryHashedPassword="	AbweD5EA	",RecoverPhoneNumber="	06 173 6042"},
new PasswordSecurity() { PassId=    36  ,UserId=    36  ,TotallySecuredVeryHashedPassword="	n2xf6XSpyyzm	",RecoverPhoneNumber="	06 440 4837"},
new PasswordSecurity() { PassId=    37  ,UserId=    37  ,TotallySecuredVeryHashedPassword="	4zaWscBbkJ	",RecoverPhoneNumber="	06 977 9280"},
new PasswordSecurity() { PassId=    38  ,UserId=    38  ,TotallySecuredVeryHashedPassword="	fMoYTVziK8	",RecoverPhoneNumber="	06 914 2168"},
new PasswordSecurity() { PassId=    39  ,UserId=    39  ,TotallySecuredVeryHashedPassword="	Z049bJai6	",RecoverPhoneNumber="	06 220 4599"},
new PasswordSecurity() { PassId=    40  ,UserId=    40  ,TotallySecuredVeryHashedPassword="	cJWIkqHw	",RecoverPhoneNumber="	06 014 1441"},
new PasswordSecurity() { PassId=    41  ,UserId=    41  ,TotallySecuredVeryHashedPassword="	0JDzJG	",RecoverPhoneNumber="	06 891 3249"},
new PasswordSecurity() { PassId=    42  ,UserId=    42  ,TotallySecuredVeryHashedPassword="	FtykbGkQQE8v	",RecoverPhoneNumber="	06 257 6846"},
new PasswordSecurity() { PassId=    43  ,UserId=    43  ,TotallySecuredVeryHashedPassword="	D2V9lwXNR	",RecoverPhoneNumber="	06 859 5286"},
new PasswordSecurity() { PassId=    44  ,UserId=    44  ,TotallySecuredVeryHashedPassword="	VJdvIzUm	",RecoverPhoneNumber="	06 807 7267"},
new PasswordSecurity() { PassId=    45  ,UserId=    45  ,TotallySecuredVeryHashedPassword="	C3ZCGl	",RecoverPhoneNumber="	06 885 5887"},
new PasswordSecurity() { PassId=    46  ,UserId=    46  ,TotallySecuredVeryHashedPassword="	8udEfNVJKJ00	",RecoverPhoneNumber="	06 650 4533"},
new PasswordSecurity() { PassId=    47  ,UserId=    47  ,TotallySecuredVeryHashedPassword="	UJVYCYx5HfVx	",RecoverPhoneNumber="	06 273 2688"},
new PasswordSecurity() { PassId=    48  ,UserId=    48  ,TotallySecuredVeryHashedPassword="	0vdZ9f	",RecoverPhoneNumber="	06 711 6901"},
new PasswordSecurity() { PassId=    49  ,UserId=    49  ,TotallySecuredVeryHashedPassword="	oTLaNj5j	",RecoverPhoneNumber="	06 956 6655"},
new PasswordSecurity() { PassId=    50  ,UserId=    50  ,TotallySecuredVeryHashedPassword="	bc30RGii5w	",RecoverPhoneNumber="	06 299 8298"},
new PasswordSecurity() { PassId=    51  ,UserId=    51  ,TotallySecuredVeryHashedPassword="	52BZ8mJKWV4	",RecoverPhoneNumber="	06 004 0470"},
new PasswordSecurity() { PassId=    52  ,UserId=    52  ,TotallySecuredVeryHashedPassword="	JVWD8eUF8s	",RecoverPhoneNumber="	06 327 5766"},
new PasswordSecurity() { PassId=    53  ,UserId=    53  ,TotallySecuredVeryHashedPassword="	GwzUa8wg	",RecoverPhoneNumber="	06 538 2939"},
new PasswordSecurity() { PassId=    54  ,UserId=    54  ,TotallySecuredVeryHashedPassword="	nmPhBqf2Hy	",RecoverPhoneNumber="	06 438 4370"},
new PasswordSecurity() { PassId=    55  ,UserId=    55  ,TotallySecuredVeryHashedPassword="	ZQQmMr3	",RecoverPhoneNumber="	06 553 1345"},
new PasswordSecurity() { PassId=    56  ,UserId=    56  ,TotallySecuredVeryHashedPassword="	zV1vPzcP	",RecoverPhoneNumber="	06 265 8577"},
new PasswordSecurity() { PassId=    57  ,UserId=    57  ,TotallySecuredVeryHashedPassword="	KKrzHqnl	",RecoverPhoneNumber="	06 711 1470"},
new PasswordSecurity() { PassId=    58  ,UserId=    58  ,TotallySecuredVeryHashedPassword="	UaootNxNSBr	",RecoverPhoneNumber="	06 193 2218"},
new PasswordSecurity() { PassId=    59  ,UserId=    59  ,TotallySecuredVeryHashedPassword="	ECG63unBXC	",RecoverPhoneNumber="	06 547 3738"},
new PasswordSecurity() { PassId=    60  ,UserId=    60  ,TotallySecuredVeryHashedPassword="	IbVPKpyW5uS	",RecoverPhoneNumber="	06 430 3331"},
new PasswordSecurity() { PassId=    61  ,UserId=    61  ,TotallySecuredVeryHashedPassword="	BHdAxqVNfLH	",RecoverPhoneNumber="	06 088 8761"},
new PasswordSecurity() { PassId=    62  ,UserId=    62  ,TotallySecuredVeryHashedPassword="	WP0R6P	",RecoverPhoneNumber="	06 889 2073"},
new PasswordSecurity() { PassId=    63  ,UserId=    63  ,TotallySecuredVeryHashedPassword="	0a5vBxn	",RecoverPhoneNumber="	06 396 0025"},
new PasswordSecurity() { PassId=    64  ,UserId=    64  ,TotallySecuredVeryHashedPassword="	xYvNuu4j7GE0	",RecoverPhoneNumber="	06 079 2853"},
new PasswordSecurity() { PassId=    65  ,UserId=    65  ,TotallySecuredVeryHashedPassword="	ingOaK3Vsv	",RecoverPhoneNumber="	06 875 4563"},
new PasswordSecurity() { PassId=    66  ,UserId=    66  ,TotallySecuredVeryHashedPassword="	KYxtGqRwj	",RecoverPhoneNumber="	06 329 8403"},
new PasswordSecurity() { PassId=    67  ,UserId=    67  ,TotallySecuredVeryHashedPassword="	ounvtbck	",RecoverPhoneNumber="	06 242 8848"},
new PasswordSecurity() { PassId=    68  ,UserId=    68  ,TotallySecuredVeryHashedPassword="	SJr0tqJYG	",RecoverPhoneNumber="	06 503 3131"},
new PasswordSecurity() { PassId=    69  ,UserId=    69  ,TotallySecuredVeryHashedPassword="	DCiFqQ9iy3B	",RecoverPhoneNumber="	06 771 0095"},
new PasswordSecurity() { PassId=    70  ,UserId=    70  ,TotallySecuredVeryHashedPassword="	jURsdsUZS	",RecoverPhoneNumber="	06 846 2413"},
new PasswordSecurity() { PassId=    71  ,UserId=    71  ,TotallySecuredVeryHashedPassword="	OWCCjZ	",RecoverPhoneNumber="	06 554 4327"},
new PasswordSecurity() { PassId=    72  ,UserId=    72  ,TotallySecuredVeryHashedPassword="	vrCZP297	",RecoverPhoneNumber="	06 352 3842"},
new PasswordSecurity() { PassId=    73  ,UserId=    73  ,TotallySecuredVeryHashedPassword="	wOqRFG5d	",RecoverPhoneNumber="	06 003 6984"},
new PasswordSecurity() { PassId=    74  ,UserId=    74  ,TotallySecuredVeryHashedPassword="	lHMerEI	",RecoverPhoneNumber="	06 186 5633"},
new PasswordSecurity() { PassId=    75  ,UserId=    75  ,TotallySecuredVeryHashedPassword="	rCSBt1WCY	",RecoverPhoneNumber="	06 679 0436"},
new PasswordSecurity() { PassId=    76  ,UserId=    76  ,TotallySecuredVeryHashedPassword="	zhZ9bLVYO	",RecoverPhoneNumber="	06 302 8640"},
new PasswordSecurity() { PassId=    77  ,UserId=    77  ,TotallySecuredVeryHashedPassword="	Ix1mij	",RecoverPhoneNumber="	06 298 9814"},
new PasswordSecurity() { PassId=    78  ,UserId=    78  ,TotallySecuredVeryHashedPassword="	z7KAIf	",RecoverPhoneNumber="	06 173 5880"},
new PasswordSecurity() { PassId=    79  ,UserId=    79  ,TotallySecuredVeryHashedPassword="	WU3AGdt	",RecoverPhoneNumber="	06 988 0171"},
new PasswordSecurity() { PassId=    80  ,UserId=    80  ,TotallySecuredVeryHashedPassword="	QkFi8o4ZDbBD	",RecoverPhoneNumber="	06 514 8025"},
new PasswordSecurity() { PassId=    81  ,UserId=    81  ,TotallySecuredVeryHashedPassword="	z2eNZ2	",RecoverPhoneNumber="	06 092 7698"},
new PasswordSecurity() { PassId=    82  ,UserId=    82  ,TotallySecuredVeryHashedPassword="	CQa3IaJ	",RecoverPhoneNumber="	06 249 4825"},
new PasswordSecurity() { PassId=    83  ,UserId=    83  ,TotallySecuredVeryHashedPassword="	uuV23z	",RecoverPhoneNumber="	06 208 4176"},
new PasswordSecurity() { PassId=    84  ,UserId=    84  ,TotallySecuredVeryHashedPassword="	PhRDRYCczQx	",RecoverPhoneNumber="	06 510 2203"},
new PasswordSecurity() { PassId=    85  ,UserId=    85  ,TotallySecuredVeryHashedPassword="	Aq6DsNEySUC	",RecoverPhoneNumber="	06 608 8407"},
new PasswordSecurity() { PassId=    86  ,UserId=    86  ,TotallySecuredVeryHashedPassword="	bsZ2wa2lX	",RecoverPhoneNumber="	06 949 5259"},
new PasswordSecurity() { PassId=    87  ,UserId=    87  ,TotallySecuredVeryHashedPassword="	0q4nGi	",RecoverPhoneNumber="	06 541 3675"},
new PasswordSecurity() { PassId=    88  ,UserId=    88  ,TotallySecuredVeryHashedPassword="	Vv8XzjZd6	",RecoverPhoneNumber="	06 377 3206"},
new PasswordSecurity() { PassId=    89  ,UserId=    89  ,TotallySecuredVeryHashedPassword="	8o5ycF	",RecoverPhoneNumber="	06 130 8987"},
new PasswordSecurity() { PassId=    90  ,UserId=    90  ,TotallySecuredVeryHashedPassword="	sOqnQE1ah2b5	",RecoverPhoneNumber="	06 315 5734"},
new PasswordSecurity() { PassId=    91  ,UserId=    91  ,TotallySecuredVeryHashedPassword="	TAif6H7uYGjf	",RecoverPhoneNumber="	06 778 4243"},
new PasswordSecurity() { PassId=    92  ,UserId=    92  ,TotallySecuredVeryHashedPassword="	Ky0fUuAX	",RecoverPhoneNumber="	06 015 4390"},
new PasswordSecurity() { PassId=    93  ,UserId=    93  ,TotallySecuredVeryHashedPassword="	4PCsa7T	",RecoverPhoneNumber="	06 726 5283"},
new PasswordSecurity() { PassId=    94  ,UserId=    94  ,TotallySecuredVeryHashedPassword="	hvoV8Ci50bU	",RecoverPhoneNumber="	06 815 6115"},
new PasswordSecurity() { PassId=    95  ,UserId=    95  ,TotallySecuredVeryHashedPassword="	bLVsAmMd	",RecoverPhoneNumber="	06 096 9169"},
new PasswordSecurity() { PassId=    96  ,UserId=    96  ,TotallySecuredVeryHashedPassword="	ZDzRbyjh668	",RecoverPhoneNumber="	06 204 5254"},
new PasswordSecurity() { PassId=    97  ,UserId=    97  ,TotallySecuredVeryHashedPassword="	iRFJgD7Ew7	",RecoverPhoneNumber="	06 041 8643"},
new PasswordSecurity() { PassId=    98  ,UserId=    98  ,TotallySecuredVeryHashedPassword="	N6jWaF76ixkw	",RecoverPhoneNumber="	06 837 9226"},
new PasswordSecurity() { PassId=    99  ,UserId=    99  ,TotallySecuredVeryHashedPassword="	UbSiUYEe	",RecoverPhoneNumber="	06 922 3109"},
new PasswordSecurity() { PassId=    100 ,UserId=    100 ,TotallySecuredVeryHashedPassword="	ImIktE6aVoS4	",RecoverPhoneNumber="	06 800 9186"}
        };

            List<RunInformation> lista3 = new List<RunInformation>()
            {
new RunInformation() { RunID=   1   ,UserID=    3   ,Distance=  36.1    ,Time="00:80:89", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   2   ,UserID=    99  ,Distance=  33.3    ,Time="00:26:78", IsCompetition=    false   ,Location="	Luxembourg	"},
new RunInformation() { RunID=   3   ,UserID=    75  ,Distance=  39  ,Time="00:87:19", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   4   ,UserID=    36  ,Distance=  45.5    ,Time="00:26:72", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   5   ,UserID=    26  ,Distance=  39.6    ,Time="00:62:58", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   6   ,UserID=    67  ,Distance=  17.4    ,Time="00:33:08", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   7   ,UserID=    19  ,Distance=  36.7    ,Time="00:39:39", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   8   ,UserID=    79  ,Distance=  43.5    ,Time="00:04:09", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   9   ,UserID=    88  ,Distance=  41.4    ,Time="00:13:13", IsCompetition=    false   ,Location="	Hungary	"},
new RunInformation() { RunID=   10  ,UserID=    6   ,Distance=  48.5    ,Time="00:23:62", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   11  ,UserID=    2   ,Distance=  10  ,Time="00:72:47", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   12  ,UserID=    7   ,Distance=  35.8    ,Time="00:07:12", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   13  ,UserID=    55  ,Distance=  4.4 ,Time="00:08:15", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   14  ,UserID=    75  ,Distance=  22.1    ,Time="00:07:68", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   15  ,UserID=    47  ,Distance=  36  ,Time="00:40:16", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   16  ,UserID=    13  ,Distance=  30  ,Time="00:28:27", IsCompetition=    true    ,Location="	Luxembourg	"},
new RunInformation() { RunID=   17  ,UserID=    32  ,Distance=  9.3 ,Time="00:54:56", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   18  ,UserID=    26  ,Distance=  9.2 ,Time="00:01:46", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   19  ,UserID=    41  ,Distance=  24.2    ,Time="00:09:69", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   20  ,UserID=    1   ,Distance=  46  ,Time="00:84:58", IsCompetition=    false   ,Location="	Spain	"},
new RunInformation() { RunID=   21  ,UserID=    42  ,Distance=  1.5 ,Time="00:27:86", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   22  ,UserID=    56  ,Distance=  24.6    ,Time="00:73:32", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   23  ,UserID=    12  ,Distance=  25.6    ,Time="00:58:95", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   24  ,UserID=    52  ,Distance=  8.2 ,Time="00:29:53", IsCompetition=    true    ,Location="	Spain	"},
new RunInformation() { RunID=   25  ,UserID=    24  ,Distance=  24.4    ,Time="00:29:69", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   26  ,UserID=    3   ,Distance=  48  ,Time="00:89:23", IsCompetition=    false   ,Location="	Germany	"},
new RunInformation() { RunID=   27  ,UserID=    40  ,Distance=  47.2    ,Time="00:41:22", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   28  ,UserID=    94  ,Distance=  7.4 ,Time="00:27:12", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   29  ,UserID=    94  ,Distance=  49.7    ,Time="00:61:57", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   30  ,UserID=    29  ,Distance=  21.4    ,Time="00:72:82", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   31  ,UserID=    91  ,Distance=  14.6    ,Time="00:23:58", IsCompetition=    false   ,Location="	Austria	"},
new RunInformation() { RunID=   32  ,UserID=    55  ,Distance=  44.2    ,Time="00:43:11", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   33  ,UserID=    34  ,Distance=  22.3    ,Time="00:79:31", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   34  ,UserID=    40  ,Distance=  13.7    ,Time="00:66:98", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   35  ,UserID=    7   ,Distance=  9.6 ,Time="00:48:77", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   36  ,UserID=    63  ,Distance=  46.3    ,Time="00:10:06", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   37  ,UserID=    69  ,Distance=  25.2    ,Time="00:21:94", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   38  ,UserID=    53  ,Distance=  23.7    ,Time="00:65:18", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   39  ,UserID=    81  ,Distance=  14.3    ,Time="00:35:04", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   40  ,UserID=    11  ,Distance=  47.7    ,Time="00:19:26", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   41  ,UserID=    62  ,Distance=  24.9    ,Time="00:37:14", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   42  ,UserID=    100 ,Distance=  25.4    ,Time="00:91:54", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   43  ,UserID=    85  ,Distance=  7.4 ,Time="00:17:43", IsCompetition=    false   ,Location="	Netherlands	"},
new RunInformation() { RunID=   44  ,UserID=    86  ,Distance=  45.4    ,Time="00:71:91", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   45  ,UserID=    45  ,Distance=  43.2    ,Time="00:17:81", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   46  ,UserID=    18  ,Distance=  14.4    ,Time="00:18:81", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   47  ,UserID=    39  ,Distance=  22.4    ,Time="00:57:78", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   48  ,UserID=    67  ,Distance=  21.2    ,Time="00:51:89", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   49  ,UserID=    11  ,Distance=  4.2 ,Time="00:15:92", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   50  ,UserID=    24  ,Distance=  25.4    ,Time="00:40:47", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   51  ,UserID=    86  ,Distance=  19.1    ,Time="00:13:81", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   52  ,UserID=    30  ,Distance=  36.3    ,Time="00:53:62", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   53  ,UserID=    2   ,Distance=  5.3 ,Time="00:39:63", IsCompetition=    false   ,Location="	Luxembourg	"},
new RunInformation() { RunID=   54  ,UserID=    29  ,Distance=  33.4    ,Time="00:03:74", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   55  ,UserID=    100 ,Distance=  19.9    ,Time="00:18:03", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   56  ,UserID=    18  ,Distance=  30  ,Time="00:13:31", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   57  ,UserID=    93  ,Distance=  22  ,Time="00:36:12", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   58  ,UserID=    9   ,Distance=  11  ,Time="00:82:71", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   59  ,UserID=    55  ,Distance=  23.9    ,Time="00:87:34", IsCompetition=    false   ,Location="	Germany	"},
new RunInformation() { RunID=   60  ,UserID=    44  ,Distance=  12.9    ,Time="00:20:60", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   61  ,UserID=    100 ,Distance=  5.5 ,Time="00:91:07", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   62  ,UserID=    12  ,Distance=  3.2 ,Time="00:11:99", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   63  ,UserID=    22  ,Distance=  42.6    ,Time="00:69:20", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   64  ,UserID=    17  ,Distance=  2.5 ,Time="00:21:06", IsCompetition=    false   ,Location="	Luxembourg	"},
new RunInformation() { RunID=   65  ,UserID=    48  ,Distance=  28.6    ,Time="00:59:96", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   66  ,UserID=    91  ,Distance=  22  ,Time="00:47:70", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   67  ,UserID=    55  ,Distance=  7   ,Time="00:51:39", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   68  ,UserID=    61  ,Distance=  5.8 ,Time="00:55:84", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   69  ,UserID=    88  ,Distance=  9.7 ,Time="00:50:69", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   70  ,UserID=    53  ,Distance=  1.7 ,Time="00:85:96", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   71  ,UserID=    72  ,Distance=  43.9    ,Time="00:80:14", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   72  ,UserID=    97  ,Distance=  36.5    ,Time="00:62:76", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   73  ,UserID=    88  ,Distance=  13.8    ,Time="00:99:73", IsCompetition=    false   ,Location="	Germany	"},
new RunInformation() { RunID=   74  ,UserID=    86  ,Distance=  36.2    ,Time="00:24:58", IsCompetition=    true    ,Location="	United Kingdom	"},
new RunInformation() { RunID=   75  ,UserID=    47  ,Distance=  35.9    ,Time="00:80:89", IsCompetition=    false   ,Location="	Netherlands	"},
new RunInformation() { RunID=   76  ,UserID=    81  ,Distance=  39.9    ,Time="00:92:37", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   77  ,UserID=    93  ,Distance=  37.1    ,Time="00:48:79", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   78  ,UserID=    1   ,Distance=  30.4    ,Time="00:63:91", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   79  ,UserID=    65  ,Distance=  44.5    ,Time="00:08:13", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   80  ,UserID=    71  ,Distance=  22.7    ,Time="00:51:03", IsCompetition=    true    ,Location="	Spain	"},
new RunInformation() { RunID=   81  ,UserID=    59  ,Distance=  42.2    ,Time="00:88:54", IsCompetition=    true    ,Location="	Austria	"},
new RunInformation() { RunID=   82  ,UserID=    88  ,Distance=  28.5    ,Time="00:56:22", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   83  ,UserID=    13  ,Distance=  35.5    ,Time="00:99:58", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   84  ,UserID=    59  ,Distance=  11.5    ,Time="00:05:63", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   85  ,UserID=    44  ,Distance=  9.3 ,Time="00:53:08", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   86  ,UserID=    85  ,Distance=  34.8    ,Time="00:62:88", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   87  ,UserID=    53  ,Distance=  5.5 ,Time="00:32:42", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   88  ,UserID=    84  ,Distance=  2   ,Time="00:87:35", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   89  ,UserID=    4   ,Distance=  33.2    ,Time="00:15:66", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   90  ,UserID=    83  ,Distance=  32.6    ,Time="00:16:08", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   91  ,UserID=    44  ,Distance=  36.9    ,Time="00:99:76", IsCompetition=    false   ,Location="	United Kingdom	"},
new RunInformation() { RunID=   92  ,UserID=    56  ,Distance=  27.7    ,Time="00:00:32", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   93  ,UserID=    81  ,Distance=  3.1 ,Time="00:24:52", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   94  ,UserID=    42  ,Distance=  24.6    ,Time="00:76:44", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   95  ,UserID=    10  ,Distance=  11.6    ,Time="00:35:53", IsCompetition=    true    ,Location="	Luxembourg	"},
new RunInformation() { RunID=   96  ,UserID=    51  ,Distance=  29.9    ,Time="00:93:14", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   97  ,UserID=    84  ,Distance=  10.2    ,Time="00:23:20", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   98  ,UserID=    92  ,Distance=  3.5 ,Time="00:22:49", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   99  ,UserID=    99  ,Distance=  45.5    ,Time="00:17:05", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   100 ,UserID=    58  ,Distance=  14.8    ,Time="00:45:13", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   101 ,UserID=    26  ,Distance=  4.9 ,Time="00:16:25", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   102 ,UserID=    77  ,Distance=  4.8 ,Time="00:31:15", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   103 ,UserID=    58  ,Distance=  29.8    ,Time="00:47:73", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   104 ,UserID=    45  ,Distance=  2.6 ,Time="00:76:27", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   105 ,UserID=    94  ,Distance=  24.2    ,Time="00:47:64", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   106 ,UserID=    9  ,Distance=  18.3    ,Time="00:37:05", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   107 ,UserID=    90  ,Distance=  20.9    ,Time="00:71:38", IsCompetition=    false   ,Location="	Germany	"},
new RunInformation() { RunID=   108 ,UserID=    71  ,Distance=  45.6    ,Time="00:17:92", IsCompetition=    true    ,Location="	Australia	"},
new RunInformation() { RunID=   109 ,UserID=    94  ,Distance=  30.5    ,Time="00:83:44", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   110 ,UserID=    74  ,Distance=  31  ,Time="00:70:15", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   111 ,UserID=    90  ,Distance=  37.8    ,Time="00:96:14", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   112 ,UserID=    20  ,Distance=  43.7    ,Time="00:41:73", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   113 ,UserID=    2   ,Distance=  4.9 ,Time="00:76:31", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   114 ,UserID=    67  ,Distance=  17.1    ,Time="00:90:20", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   115 ,UserID=    73  ,Distance=  7   ,Time="00:28:56", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   116 ,UserID=    41  ,Distance=  49.4    ,Time="00:28:68", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   117 ,UserID=    78  ,Distance=  33.6    ,Time="00:54:01", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   118 ,UserID=    80  ,Distance=  28.8    ,Time="00:27:98", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   119 ,UserID=    63  ,Distance=  15.6    ,Time="00:81:20", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   120 ,UserID=    13  ,Distance=  4   ,Time="00:43:93", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   121 ,UserID=    53  ,Distance=  45.5    ,Time="00:44:60", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   122 ,UserID=    27  ,Distance=  6.4 ,Time="00:38:26", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   123 ,UserID=    61  ,Distance=  11.6    ,Time="00:34:96", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   124 ,UserID=    20  ,Distance=  11.7    ,Time="00:28:78", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   125 ,UserID=    32  ,Distance=  9.3 ,Time="00:18:93", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   126 ,UserID=    89  ,Distance=  3.4 ,Time="00:07:14", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   127 ,UserID=    8   ,Distance=  21.6    ,Time="00:83:62", IsCompetition=    true    ,Location="	United Kingdom	"},
new RunInformation() { RunID=   128 ,UserID=    37  ,Distance=  20.3    ,Time="00:65:93", IsCompetition=    false   ,Location="	Germany	"},
new RunInformation() { RunID=   129 ,UserID=    20  ,Distance=  3.3 ,Time="00:81:04", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   130 ,UserID=    99  ,Distance=  9.2 ,Time="00:58:69", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   131 ,UserID=    98  ,Distance=  27.8    ,Time="00:94:16", IsCompetition=    false   ,Location="	Germany	"},
new RunInformation() { RunID=   132 ,UserID=    82  ,Distance=  27.5    ,Time="00:38:15", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   133 ,UserID=    12  ,Distance=  37.3    ,Time="00:11:66", IsCompetition=    false   ,Location="	Germany	"},
new RunInformation() { RunID=   134 ,UserID=    15  ,Distance=  24.5    ,Time="00:76:96", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   135 ,UserID=    33  ,Distance=  49.6    ,Time="00:00:11", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   136 ,UserID=    99  ,Distance=  43.3    ,Time="00:96:55", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   137 ,UserID=    23  ,Distance=  33.5    ,Time="00:44:69", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   138 ,UserID=    21  ,Distance=  32.5    ,Time="00:25:16", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   139 ,UserID=    36  ,Distance=  33.3    ,Time="00:60:82", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   140 ,UserID=    16  ,Distance=  9   ,Time="00:80:99", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   141 ,UserID=    79  ,Distance=  42.9    ,Time="00:77:92", IsCompetition=    true    ,Location="	Netherlands	"},
new RunInformation() { RunID=   142 ,UserID=    16  ,Distance=  37.3    ,Time="00:69:48", IsCompetition=    true    ,Location="	Spain	"},
new RunInformation() { RunID=   143 ,UserID=    77  ,Distance=  14.5    ,Time="00:97:22", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   144 ,UserID=    61  ,Distance=  1.6 ,Time="00:07:44", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   145 ,UserID=    92  ,Distance=  8.1 ,Time="00:00:12", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   146 ,UserID=    87  ,Distance=  30.2    ,Time="00:01:11", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   147 ,UserID=    81  ,Distance=  6.1 ,Time="00:26:02", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   148 ,UserID=    57  ,Distance=  25.8    ,Time="00:73:76", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   149 ,UserID=    63  ,Distance=  2.5 ,Time="00:29:28", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   150 ,UserID=    49  ,Distance=  14.7    ,Time="00:95:70", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   151 ,UserID=    66  ,Distance=  37.7    ,Time="00:55:23", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   152 ,UserID=    52  ,Distance=  16.7    ,Time="00:15:98", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   153 ,UserID=    29  ,Distance=  36.2    ,Time="00:82:59", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   154 ,UserID=    13  ,Distance=  20.4    ,Time="00:72:18", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   155 ,UserID=    6   ,Distance=  26.1    ,Time="00:81:50", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   156 ,UserID=    57  ,Distance=  11.2    ,Time="00:00:97", IsCompetition=    true    ,Location="	Netherlands	"},
new RunInformation() { RunID=   157 ,UserID=    20  ,Distance=  19.3    ,Time="00:26:72", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   158 ,UserID=    42  ,Distance=  17.5    ,Time="00:79:25", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   159 ,UserID=    62  ,Distance=  48.9    ,Time="00:02:18", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   160 ,UserID=    4   ,Distance=  12.8    ,Time="00:48:68", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   161 ,UserID=    72  ,Distance=  2.2 ,Time="00:20:61", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   162 ,UserID=    1   ,Distance=  5.3 ,Time="00:41:71", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   163 ,UserID=    47  ,Distance=  3.1 ,Time="00:86:55", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   164 ,UserID=    72  ,Distance=  13.7    ,Time="00:91:07", IsCompetition=    true    ,Location="	Netherlands	"},
new RunInformation() { RunID=   165 ,UserID=    11  ,Distance=  46.6    ,Time="00:81:58", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   166 ,UserID=    46  ,Distance=  29.2    ,Time="00:32:85", IsCompetition=    false   ,Location="	Germany	"},
new RunInformation() { RunID=   167 ,UserID=    40  ,Distance=  33.2    ,Time="00:49:09", IsCompetition=    true    ,Location="	Netherlands	"},
new RunInformation() { RunID=   168 ,UserID=    68  ,Distance=  29.9    ,Time="00:04:82", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   169 ,UserID=    99  ,Distance=  17.7    ,Time="00:78:33", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   170 ,UserID=    49  ,Distance=  30.5    ,Time="00:44:79", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   171 ,UserID=    55  ,Distance=  39.1    ,Time="00:45:59", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   172 ,UserID=    92  ,Distance=  17  ,Time="00:04:04", IsCompetition=    false   ,Location="	Netherlands	"},
new RunInformation() { RunID=   173 ,UserID=    42  ,Distance=  1.7 ,Time="00:93:16", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   174 ,UserID=    47  ,Distance=  25.6    ,Time="00:46:74", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   175 ,UserID=    25  ,Distance=  26.3    ,Time="00:50:75", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   176 ,UserID=    43  ,Distance=  19.6    ,Time="00:99:98", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   177 ,UserID=    64  ,Distance=  10.9    ,Time="00:38:69", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   178 ,UserID=    28  ,Distance=  2.2 ,Time="00:84:06", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   179 ,UserID=    8   ,Distance=  21.6    ,Time="00:99:33", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   180 ,UserID=    90  ,Distance=  8   ,Time="00:04:16", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   181 ,UserID=    47  ,Distance=  47.4    ,Time="00:67:38", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   182 ,UserID=    79  ,Distance=  34.8    ,Time="00:34:13", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   183 ,UserID=    23  ,Distance=  12.2    ,Time="00:80:11", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   184 ,UserID=    1   ,Distance=  26.1    ,Time="00:05:97", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   185 ,UserID=    37  ,Distance=  33.4    ,Time="00:17:38", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   186 ,UserID=    10  ,Distance=  24.9    ,Time="00:71:44", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   187 ,UserID=    98  ,Distance=  19  ,Time="00:70:50", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   188 ,UserID=    76  ,Distance=  24.8    ,Time="00:85:62", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   189 ,UserID=    63  ,Distance=  42.3    ,Time="00:84:14", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   190 ,UserID=    52  ,Distance=  7.5 ,Time="00:54:48", IsCompetition=    false   ,Location="	Poland	"},
new RunInformation() { RunID=   191 ,UserID=    22  ,Distance=  47.4    ,Time="00:72:31", IsCompetition=    true    ,Location="	Poland	"},
new RunInformation() { RunID=   192 ,UserID=    36  ,Distance=  45.8    ,Time="00:98:45", IsCompetition=    true    ,Location="	Luxembourg	"},
new RunInformation() { RunID=   193 ,UserID=    44  ,Distance=  8.4 ,Time="00:01:21", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   194 ,UserID=    82  ,Distance=  48.5    ,Time="00:36:32", IsCompetition=    true    ,Location="	United States	"},
new RunInformation() { RunID=   195 ,UserID=    32  ,Distance=  33.8    ,Time="00:16:94", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   196 ,UserID=    74  ,Distance=  43  ,Time="00:53:49", IsCompetition=    false   ,Location="	United States	"},
new RunInformation() { RunID=   197 ,UserID=    92  ,Distance=  1.5 ,Time="00:62:33", IsCompetition=    false   ,Location="	Japan	"},
new RunInformation() { RunID=   198 ,UserID=    87  ,Distance=  37.5    ,Time="00:36:64", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   199 ,UserID=    57  ,Distance=  11.5    ,Time="00:70:21", IsCompetition=    true    ,Location="	Japan	"},
new RunInformation() { RunID=   200 ,UserID=    2   ,Distance=  45.4    ,Time="00:91:68", IsCompetition=    false   ,Location="	Poland	"},

            };


            



            modelBuilder.Entity<RunInformation>().HasData(lista3);
            modelBuilder.Entity<PasswordSecurity>().HasData(lista2);
            modelBuilder.Entity<UserInformation>().HasData(listau);

        }

    }
}
